"""
Django settings for ua_clinic_backend project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

Project-specific notes (presentation-friendly):
- Uses DRF + SimpleJWT for API authentication.
- Uses CORS headers to allow the Expo frontend to call the backend.
- Uses `AES_MASTER_KEY_B64` (base64) for AES-GCM encryption of sensitive fields.
- Supports either Postgres via `DATABASE_URL` or a SQLite fallback.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Repo root is one level above the Django project folder (backend/..)
REPO_ROOT = BASE_DIR.parent

# Load environment variables from .env at repo root (if present)
load_dotenv(REPO_ROOT / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

def _normalize_host(value: str) -> str:
    value = (value or "").strip()
    if not value:
        return ""
    # Render users sometimes paste full URLs; Django expects hostnames.
    value = value.replace("https://", "").replace("http://", "")
    # Strip path if present
    value = value.split("/", 1)[0]
    return value


ALLOWED_HOSTS = [
    _normalize_host(h)
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if _normalize_host(h)
]

# Render sets this automatically to your service hostname (e.g., aes-back.onrender.com)
render_host = _normalize_host(os.environ.get("RENDER_EXTERNAL_HOSTNAME", ""))
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

# Railway sets public/private domains for each service.
railway_public_domain = _normalize_host(os.environ.get("RAILWAY_PUBLIC_DOMAIN", ""))
if railway_public_domain and railway_public_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_public_domain)

railway_private_domain = _normalize_host(os.environ.get("RAILWAY_PRIVATE_DOMAIN", ""))
if railway_private_domain and railway_private_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_private_domain)

if DEBUG and not ALLOWED_HOSTS:
    # Development default: allow local + LAN (e.g., phone hitting your machine IP)
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local
    'clinic.apps.ClinicConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Common reverse-proxy settings (Railway/Render/etc.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# CORS (development-friendly defaults; tighten for production)
CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "true").lower() == "true"

if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
        if o.strip()
    ]

ROOT_URLCONF = 'ua_clinic_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ua_clinic_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    # Render Postgres (or any hosted Postgres) for persistence across deploys.
    default_db = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=not DEBUG,
    )

    # Some platforms (including some Render environments) may lack IPv6 egress.
    # Supabase DNS can return IPv6 first; psycopg2/libpq may then fail with
    # "Network is unreachable". Setting DATABASE_HOSTADDR to an IPv4 address
    # forces the TCP connection to use IPv4 while preserving the hostname for
    # TLS/cert validation.
    hostaddr = os.environ.get("DATABASE_HOSTADDR", "").strip()
    if hostaddr:
        default_db.setdefault("OPTIONS", {})
        default_db["OPTIONS"]["hostaddr"] = hostaddr

    DATABASES = {"default": default_db}
else:
    # Local/dev fallback
    # NOTE: On Render without Postgres, you can attach a Persistent Disk and set
    # SQLITE_PATH=/var/data/db.sqlite3 so the DB survives restarts.
    sqlite_path = os.environ.get("SQLITE_PATH", "").strip()

    # Convenience: if a Render Persistent Disk is mounted at /var/data and SQLITE_PATH
    # isn't set, use a stable default path so accounts persist.
    if not sqlite_path:
        try:
            if os.path.isdir("/var/data"):
                sqlite_path = "/var/data/db.sqlite3"
        except Exception:
            sqlite_path = ""

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path or (BASE_DIR / 'db.sqlite3'),
        }
    }

# DRF / JWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# AES-GCM master key (base64). Required for encryption/decryption.
AES_MASTER_KEY_B64 = os.environ.get("AES_MASTER_KEY_B64", "")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise will serve collected static files when DEBUG=False.
if not DEBUG:
    # Manifest storage is stricter and can raise 500s if collectstatic wasn't run
    # (common misconfig on new deploy platforms). CompressedStaticFilesStorage
    # is more forgiving while still producing gzip/brotli variants.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    # As a safety net, allow serving via Django's staticfiles finders.
    # (You should still run collectstatic for best performance.)
    WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
